version: '3.5'
services:
  coder:
    container_name: code-server
    build:
      context: ./coder
    environment:
      - DEBUG_ENTRYPOINT=2
    volumes:
      - source_code:/home/coder/project/
      - coder_setting:/home/coder/
      - ./coder/coder-run.d/:/run.d/
    ports:
      - "8443:8443"

volumes:
  source_code: null
  coder_setting: null