version: '3.7'
services:
  code:
    container_name: code
    image: chrishsieh/develop_php:code-server
#    build:
#      context: ./build/coder
    environment:
      DEBUG_ENTRYPOINT: 2
      CODESERVER_PARAMETER: ${DEV_CODESERVER_PARA:--allow-http --no-auth}
      FORWARD_PORTS_TO_LOCALHOST: ${DEV_WEB_PORT:-80}:web:80
      EN_XDEBUG: ${DEV_EN_XDEBUG:-false}
      MYSQL_DB_HOST: ${MYSQL_DB_HOST:-db}
    volumes:
      - source_code:/var/www/
      - coder_setting:/home/coder/
      - ./runtime/coder/run.d/:/run.d/
    ports:
      - "8443:8443"
    links:
      - db

  db:
    container_name: db
#    image: mariadb
    image: yobasystems/alpine-mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "${DEV_WEB_PORT:-80}:80"
    links:
      - code
    volumes:
      - source_code:/var/www/
      - ./runtime/nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  source_code: null
  coder_setting: null
  db_data: null