version: '3.5'
services:
  coder:
    container_name: code-server
    build:
      context: .
      dockerfile: Dockerfile.coder
    environment:
      - MOUNT_UID=${MOUNT_UID:-82}
    volumes:
      - source_code:/home/coder/project/
      - coder_setting:/home/coder/
    ports:
      - "8443:8443"

volumes:
  source_code: null
  coder_setting: null