version: '3.7'
services:
  coder:
    container_name: code-server
    image: chrishsieh/develop_php:code-server
    build:
      context: ./build/coder
    environment:
      DEBUG_ENTRYPOINT: 2
      CODESERVER_PARAMETER: --allow-http --no-auth
      FORWARD_PORTS_TO_LOCALHOST: 8080:webserver:80
    volumes:
      - source_code:/home/coder/project/
      - coder_setting:/home/coder/
      - ./runtime/coder/run.d/:/run.d/
    ports:
      - "8443:8443"
    links:
      - database

  database:
    image: mariadb
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql

  webserver:
    build:
      context: ./build/nginx
    ports:
      - "8080:80"
    links:
      - coder
    volumes:
      - source_code:/var/www/code/
      - ./runtime/nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  source_code: null
  coder_setting: null
  db-volume: null