version: '3.7'
services:
  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - "${DEV_MAILCATCHER_PORT:-1080}:1080"

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    environment:
      - VNC_NO_PASSWORD=1
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
